# Generated by Django 3.1.4 on 2020-12-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comps',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='comps',
            name='town',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
