# Generated by Django 3.1.4 on 2020-12-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0002_auto_20201208_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comps',
            old_name='town',
            new_name='city',
        ),
    ]
