# Generated by Django 3.1.4 on 2020-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_auto_20201208_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comps',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
