# Generated by Django 3.1.4 on 2020-12-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0004_auto_20201208_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comps',
            name='is_final',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='min_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='result_system',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
