# Generated by Django 3.1.4 on 2020-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0007_auto_20201209_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comps',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='is_final',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='min_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='result_system',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comps',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
