# Generated by Django 3.1.4 on 2020-12-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0008_auto_20201210_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comps.comps')),
            ],
        ),
    ]
