# Generated by Django 3.1.4 on 2020-12-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0011_remove_category_comp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comps.comps'),
        ),
    ]
