# Generated by Django 3.1.4 on 2020-12-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201212_2326'),
        ('comps', '0012_category_comp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comps.category')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.racer')),
            ],
        ),
    ]
