# Generated by Django 3.1.4 on 2020-12-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0013_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sex',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
