# Generated by Django 3.1.4 on 2020-12-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0014_category_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='boulder_1_top',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_1_top_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_1_zone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_1_zone_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_2_top',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_2_top_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_2_zone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_2_zone_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_3_top',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_3_top_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_3_zone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_3_zone_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_4_top',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_4_top_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_4_zone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_4_zone_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_5_top',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_5_zone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_6_top',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='boulder_6_zone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='lead_route_1',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='lead_route_2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='lead_route_3',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='lead_route_4',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='lead_route_final',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='speeed_1',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='speeed_2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='speeed_3',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='speeed_4',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
