# Generated by Django 3.1.4 on 2021-01-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0016_auto_20201224_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='speeed_1',
            new_name='speed_1',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='speeed_2',
            new_name='speed_2',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='speeed_3',
            new_name='speed_3',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='speeed_4',
            new_name='speed_4',
        ),
        migrations.RemoveField(
            model_name='comps',
            name='result_system',
        ),
    ]
