# Generated by Django 3.1.4 on 2021-01-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0017_auto_20210101_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comps',
            name='is_final',
        ),
    ]
