# Generated by Django 3.1.4 on 2020-12-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201212_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='sex',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
