# Generated by Django 3.1.4 on 2020-12-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_racer_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='club',
            field=models.CharField(default='-', max_length=50, null=True),
        ),
    ]
