# Generated by Django 3.1.4 on 2020-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201222_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='club',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
